name: Publish .NET Linux-64
 
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish
        run: dotnet publish --configuration Release --runtime linux-x64 --output "publish" --self-contained false
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: publish-linux-x64
          path: publish
